const SUPABASE_URL = "https://oyrdgyemgzlgrjppdswb.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cmRneWVtZ3psZ3JqcHBkc3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2NDIzMDQsImV4cCI6MjA5NjIxODMwNH0.UCsV-vuQF8MgL0QL1PgpklVb8kV7YSTasBJ7F4X6Bjk";
const TOSS_CLIENT_KEY = "test_ck_BX7zk2yd8yn5mKaDDD6v3x9POLqK";
